version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:4.3.2-management-alpine
    container_name: stayhub-rabbitmq
    ports:
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USERNAME}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    restart: always

  app:
    image: ${DOCKER_USERNAME}/stayhub-backend:latest
    container_name: stayhub-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=${RABBITMQ_USERNAME}
      - SPRING_RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - TZ=Asia/Ho_Chi_Minh
    env_file:
      - .env
    depends_on:
      - rabbitmq
    logging:
      driver: "loki"
      options:
        loki-url: "http://localhost:3100/loki/api/v1/push"
        loki-batch-size: "400"
    restart: always