spring:
  application:
    name: backend
  profiles:
    active: dev
  flyway:
    enabled: true
  jpa:
    properties:
      hibernate:
        default_batch_fetch_size: 100
  mail:
    from: stayhub.noreply@gmail.com
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

application:
  security:
    jwt:
      secret-key: ${SECRET_KEY}
      expiration-ms: 900000
      refresh-token:
        expiration-ms: 604800000
  frontend:
    url: "https://getstayhub.me"

vnpay:
  tmn-code: ${VNPAY_TMN_CODE}
  hash-secret: ${VNPAY_HASH_SECRET}
  pay-url: ${VNPAY_PAY_URL}
  return-url: ${VNPAY_RETURN_URL}
  api-url: ${VNPAY_API_URL}
  version: "2.1.0"
  command: "pay"

integration:
  sepay:
    merchant-id: ${SEPAY_MERCHANT_ID}
    secret-key: ${SEPAY_SECRET_KEY}
    prefix: "STAYHUB"
    checkout-url : ${SEPAY_CHECKOUT_URL}

server:
  servlet:
    context-path: /api/v1
  address: 127.0.0.1

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
    disable-swagger-default-url: true
    display-request-duration: true
    try-it-out-enabled: true
    supported-submit-methods: ["get", "post", "put", "delete", "patch"]
    show-extensions: true
    show-common-extensions: true
  show-actuator: true
  paths-to-match: /**
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  writer-with-default-pretty-printer: true

logging:
  file:
    name: /home/ubuntu/app/logs/app.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
  level:
    org.springframework.security.config.annotation.authentication.configuration.InitializeUserDetailsBeanManagerConfigurer: ERROR