spring:
  application:
    name: backend
  profiles:
    active: dev
  flyway:
    enabled: true
  mail:
    from: ${MAIL_FROM}
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

application:
  security:
    jwt:
      secret-key: ${SECRET_KEY}
      expiration-ms: 900000
      refresh-token:
        expiration: 604800000
  frontend:
    url: "https://getstayhub.me"

server:
  servlet:
    context-path: /api/v1

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
    disable-swagger-default-url: true
    display-request-duration: true
  show-actuator: true
  paths-to-match: /**