ALTER TABLE properties ALTER COLUMN status DROP DEFAULT;
ALTER TABLE properties ALTER COLUMN status TYPE VARCHAR(50) USING status::text;
ALTER TABLE properties ALTER COLUMN status SET DEFAULT 'DRAFT';
