name: Deploy Spring Boot to AWS (Develop)

on:
  push:
    branches:
      - develop

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout mã nguồn
        uses: actions/checkout@v4

      - name: Thiết lập môi trường Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Kiểm tra kết nối mạng tới AWS
        run: nc -zv -w 5 ${{ secrets.EC2_HOST }} 22

      - name: Đóng gói ứng dụng bằng Maven
        run: mvn clean package -DskipTests

      - name: Đổi tên file Jar thành backend.jar
        run: |
          rm -f target/*-plain.jar # Xóa file plain 
          mv target/*.jar target/backend.jar

      - name: Đẩy tệp thực thi lên máy chủ AWS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "target/backend.jar"
          target: "/home/ubuntu/app/"
          strip_components: 1

      - name: Thực thi và khởi động lại dịch vụ trên AWS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo systemctl restart backend